export default {
    getDefault: () => ({
        "c𝄫": { right: 1, wrong: 1 },
        "c♭": { right: 1, wrong: 1 },
        "c": { right: 1, wrong: 1 },
        "c♯": { right: 1, wrong: 1 },
        "c𝄪": { right: 1, wrong: 1 },
        "d𝄫": { right: 1, wrong: 1 },
        "d♭": { right: 1, wrong: 1 },
        "d": { right: 1, wrong: 1 },
        "d♯": { right: 1, wrong: 1 },
        "d𝄪": { right: 1, wrong: 1 },
        "e𝄫": { right: 1, wrong: 1 },
        "e♭": { right: 1, wrong: 1 },
        "e": { right: 1, wrong: 1 },
        "e♯": { right: 1, wrong: 1 },
        "e𝄪": { right: 1, wrong: 1 },
        "f𝄫": { right: 1, wrong: 1 },
        "f♭": { right: 1, wrong: 1 },
        "f": { right: 1, wrong: 1 },
        "f♯": { right: 1, wrong: 1 },
        "f𝄪": { right: 1, wrong: 1 },
        "g𝄫": { right: 1, wrong: 1 },
        "g♭": { right: 1, wrong: 1 },
        "g": { right: 1, wrong: 1 },
        "g♯": { right: 1, wrong: 1 },
        "g𝄪": { right: 1, wrong: 1 },
        "a𝄫": { right: 1, wrong: 1 },
        "a♭": { right: 1, wrong: 1 },
        "a": { right: 1, wrong: 1 },
        "a♯": { right: 1, wrong: 1 },
        "a𝄪": { right: 1, wrong: 1 },
        "b𝄫": { right: 1, wrong: 1 },
        "b♭": { right: 1, wrong: 1 },
        "b": { right: 1, wrong: 1 },
        "b♯": { right: 1, wrong: 1 },
        "b𝄪": { right: 1, wrong: 1 },
    })
};
